apiVersion: batch/v1
kind: Job
metadata:
  name: paolo-job
  namespace: mlflow
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: paolo-job
        image: pscarpino/mlflow-docker-example
        command: ["python", "train.py", "--alpha 0.1 --l1-ratio 0.1"]
      resources:
        limits:
          memory: 512Mi
        requests:
          memory: 256Mi
      restartPolicy: Never
